apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-depl
  template:
    metadata:
      labels:
        app: myapp-depl
    spec:
      containers:
      - name: myapp-depl
        image: perischepkemoi/dockerpythondjango
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8000
